-- =====================================================================
-- STEP 1: CLEANUP (Ignore errors on the very first run)
-- =====================================================================
DROP TABLE fees CASCADE CONSTRAINTS;
DROP TABLE attendance CASCADE CONSTRAINTS;
DROP TABLE enrollments CASCADE CONSTRAINTS;
DROP TABLE courses CASCADE CONSTRAINTS;
DROP TABLE semesters CASCADE CONSTRAINTS;
DROP TABLE instructors CASCADE CONSTRAINTS;
DROP TABLE students CASCADE CONSTRAINTS;
DROP TABLE departments CASCADE CONSTRAINTS;

-- =====================================================================
-- STEP 2: CREATE TABLES (Core Structure)
-- =====================================================================
CREATE TABLE departments (
    dept_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name   VARCHAR2(100) NOT NULL UNIQUE,
    dept_head   VARCHAR2(100)
);

CREATE TABLE instructors (
    instructor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(100) NOT NULL,
    dept_id       NUMBER NOT NULL REFERENCES departments(dept_id),
    email         VARCHAR2(150) UNIQUE NOT NULL,
    salary        NUMBER(10,2) CHECK (salary > 0)
);

CREATE TABLE students (
    student_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR2(100) NOT NULL,
    dept_id         NUMBER NOT NULL REFERENCES departments(dept_id),
    dob             DATE NOT NULL,
    email           VARCHAR2(150) UNIQUE NOT NULL,
    enrollment_year NUMBER(4) NOT NULL
);

CREATE TABLE semesters (
    semester_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_name VARCHAR2(50) NOT NULL UNIQUE,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL
);

CREATE TABLE courses (
    course_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code   VARCHAR2(20) NOT NULL UNIQUE,
    course_name   VARCHAR2(100) NOT NULL,
    dept_id       NUMBER NOT NULL REFERENCES departments(dept_id),
    credits       NUMBER(1) NOT NULL CHECK (credits BETWEEN 1 AND 6),
    instructor_id NUMBER REFERENCES instructors(instructor_id)
);

CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    NUMBER NOT NULL REFERENCES students(student_id),
    course_id     NUMBER NOT NULL REFERENCES courses(course_id),
    semester_id   NUMBER NOT NULL REFERENCES semesters(semester_id),
    marks         NUMBER(5,2) CHECK (marks BETWEEN 0 AND 100),
    UNIQUE (student_id, course_id, semester_id)
);

CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    NUMBER NOT NULL REFERENCES students(student_id),
    course_id     NUMBER NOT NULL REFERENCES courses(course_id),
    class_date    DATE NOT NULL,
    status        VARCHAR2(10) NOT NULL CHECK (status IN ('Present','Absent','Late'))
);

CREATE TABLE fees (
    fee_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   NUMBER NOT NULL REFERENCES students(student_id),
    semester_id  NUMBER NOT NULL REFERENCES semesters(semester_id),
    amount_due   NUMBER(10,2) NOT NULL,
    amount_paid  NUMBER(10,2) DEFAULT 0 NOT NULL
);

-- =====================================================================
-- STEP 3: INDEXES (Speeds up database searches)
-- =====================================================================
CREATE INDEX idx_students_dept       ON students(dept_id);
CREATE INDEX idx_courses_dept        ON courses(dept_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_course  ON enrollments(course_id);
CREATE INDEX idx_attendance_student  ON attendance(student_id);
CREATE INDEX idx_fees_student        ON fees(student_id);

COMMIT;

-- =====================================================================
-- STEP 4: QUERIES (Run these after you insert your data)
-- =====================================================================

-- 1. Student Report Card (Calculates Grade on the fly instead of a trigger)
SELECT 
    s.full_name AS student_name, 
    c.course_name, 
    sem.semester_name, 
    e.marks,
    CASE 
        WHEN e.marks >= 90 THEN 'A'
        WHEN e.marks >= 75 THEN 'B'
        WHEN e.marks >= 60 THEN 'C'
        WHEN e.marks >= 50 THEN 'D'
        ELSE 'F'
    END AS calculated_grade
FROM enrollments e
JOIN students s    ON e.student_id = s.student_id
JOIN courses c     ON e.course_id = c.course_id
JOIN semesters sem ON e.semester_id = sem.semester_id;

-- 2. Outstanding Fee Balances (Calculates Status on the fly instead of a trigger)
SELECT 
    s.full_name AS student_name, 
    sem.semester_name, 
    f.amount_due, 
    f.amount_paid,
    (f.amount_due - f.amount_paid) AS balance_remaining,
    CASE
        WHEN f.amount_paid >= f.amount_due THEN 'Paid'
        WHEN f.amount_paid > 0 THEN 'Partial'
        ELSE 'Unpaid'
    END AS fee_status
FROM fees f
JOIN students s    ON f.student_id = s.student_id
JOIN semesters sem ON f.semester_id = sem.semester_id
WHERE (f.amount_due - f.amount_paid) > 0;

-- 3. Department Summary Dashboard (Counts totals)
SELECT 
    d.dept_name, 
    COUNT(DISTINCT s.student_id) AS total_students,
    COUNT(DISTINCT c.course_id)  AS total_courses,
    ROUND(AVG(e.marks), 2)       AS avg_marks
FROM departments d
LEFT JOIN students s    ON s.dept_id = d.dept_id
LEFT JOIN courses c     ON c.dept_id = d.dept_id
LEFT JOIN enrollments e ON e.student_id = s.student_id
GROUP BY d.dept_name;

-- 4. Course load per instructor
SELECT 
    i.full_name AS instructor_name, 
    COUNT(c.course_id) AS courses_taught
FROM instructors i
JOIN courses c ON c.instructor_id = i.instructor_id
GROUP BY i.full_name;